name: vending_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  url_launcher:
  share_plus:
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SFL
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
    - family: SFR
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf